/* A packrat parser generated by PackCC 3.0.0 */

#ifndef PCC_INCLUDED_PARSER_H
#define PCC_INCLUDED_PARSER_H

#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include "../utils/ast.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct vibe_context_tag vibe_context_t;

vibe_context_t *vibe_create(const char *auxil);
int vibe_parse(vibe_context_t *ctx, ast_node_t **ret);
const char *vibe_get_error(vibe_context_t *ctx);
void vibe_destroy(vibe_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED_PARSER_H */
