/**
 * Generated by VibeLanguage Compiler
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "vibelang.h"

/* Type Greeting with meaning "a friendly greeting" and base type String */
typedef char* Greeting;

/* Type Language with meaning "language name" and base type String */
typedef char* Language;

void generateGreeting(void name, void language) {
    {
    {
        // Prompt block: "Generate a friendly greeting for a person named {name} in {language}."
        const char* prompt_template = "Generate a friendly greeting for a person named {name} in {language}.";
        int var_count = 2;
        char** var_names = malloc(sizeof(char*) * var_count);
        char** var_values = malloc(sizeof(char*) * var_count);
        var_names[0] = "name";
        var_values[0] = name ? strdup(name) : strdup("");
        var_names[1] = "language";
        var_values[1] = language ? strdup(language) : strdup("");
        char* formatted_prompt = format_prompt(prompt_template, var_names, var_values, var_count);
        VibeValue* prompt_result = vibe_execute_prompt(formatted_prompt, "Generate a friendly greeting for a person named {name} in {language}.");
        
        // Free resources
        free(formatted_prompt);
        for (int i = 0; i < var_count; i++) {
            free(var_values[i]);
        }
        free(var_names);
        free(var_values);
        
        // Return the result
        return vibe_value_get_string(prompt_result);
    }
    }
}

